data = [
    {
        "name": "Cristiano Ronaldo",
        "follower_count": 663180000,
        "description": "Professional footballer, Al Nassr",
        "country": "Portugal",
    },
    {
        "name": "Lionel Messi",
        "follower_count": 506251000,
        "description": "Professional footballer, Inter Miami",
        "country": "Argentina",
    },
    {
        "name": "Selena Gomez",
        "follower_count": 417686000,
        "description": "Singer, actress, businesswoman",
        "country": "USA",
    },
    {
        "name": "Kylie Jenner",
        "follower_count": 393000000,
        "description": "Media personality, founder Kylie Cosmetics",
        "country": "USA",
    },
    {
        "name": "Dwayne Johnson",
        "follower_count": 393000000,
        "description": "Actor, producer, former wrestler",
        "country": "USA",
    },
    {
        "name": "Ariana Grande",
        "follower_count": 390000000,
        "description": "Singer, actress, songwriter",
        "country": "USA",
    },
    {
        "name": "Taylor Swift",
        "follower_count": 283000000,
        "description": "Singer, songwriter, actress",
        "country": "USA",
    },
    {
        "name": "Kim Kardashian",
        "follower_count": 370000000,
        "description": "Media personality, founder SKIMS",
        "country": "USA",
    },
    {
        "name": "Beyoncé",
        "follower_count": 315000000,
        "description": "Singer, actress, dancer",
        "country": "USA",
    },
    {
        "name": "Khloé Kardashian",
        "follower_count": 302000000,
        "description": "Media personality, businesswoman",
        "country": "USA",
    },
    {
        "name": "Virat Kohli",
        "follower_count": 270000000,
        "description": "Professional cricketer, India captain",
        "country": "India",
    },
    {
        "name": "Kendall Jenner",
        "follower_count": 299000000,
        "description": "Model, media personality",
        "country": "USA",
    },
    {
        "name": "National Geographic",
        "follower_count": 281000000,
        "description": "Documentary photography platform",
        "country": "USA",
    },
    {
        "name": "Justin Bieber",
        "follower_count": 281000000,
        "description": "Singer, songwriter, musician",
        "country": "Canada",
    },
    {
        "name": "Neymar Jr",
        "follower_count": 220000000,
        "description": "Professional footballer",
        "country": "Brazil",
    },
    {
        "name": "Miley Cyrus",
        "follower_count": 210000000,
        "description": "Singer, actress, songwriter",
        "country": "USA",
    },
    {
        "name": "Ellen DeGeneres",
        "follower_count": 209000000,
        "description": "Comedian, talk show host",
        "country": "USA",
    },
    {
        "name": "Jennifer Lopez",
        "follower_count": 251000000,
        "description": "Singer, actress, dancer, businesswoman",
        "country": "USA",
    },
    {
        "name": "Cardi B",
        "follower_count": 221000000,
        "description": "Rapper, songwriter, media personality",
        "country": "USA",
    },
    {
        "name": "Rihanna",
        "follower_count": 233000000,
        "description": "Singer, actress, businesswoman",
        "country": "Barbados",
    },
    {
        "name": "Katy Perry",
        "follower_count": 192000000,
        "description": "Singer, songwriter, actress",
        "country": "USA",
    },
    {
        "name": "Dua Lipa",
        "follower_count": 194000000,
        "description": "Singer, songwriter, model",
        "country": "United Kingdom",
    },
    {
        "name": "Daniel Radcliffe",
        "follower_count": 76000000,
        "description": "Actor",
        "country": "United Kingdom",
    },
    {
        "name": "Chris Hemsworth",
        "follower_count": 259000000,
        "description": "Actor, producer",
        "country": "Australia",
    },
    {
        "name": "Zendaya",
        "follower_count": 190000000,
        "description": "Actress, dancer, model, singer",
        "country": "USA",
    },
    {
        "name": "Tom Cruise",
        "follower_count": 35000000,
        "description": "Actor, producer",
        "country": "USA",
    },
    {
        "name": "Emma Watson",
        "follower_count": 77000000,
        "description": "Actress, activist",
        "country": "United Kingdom",
    },
    {
        "name": "Gigi Hadid",
        "follower_count": 200000000,
        "description": "Model, businesswoman",
        "country": "USA",
    },
    {
        "name": "Bella Hadid",
        "follower_count": 153000000,
        "description": "Model, businesswoman",
        "country": "USA",
    },
    {
        "name": "Cristina Aguilera",
        "follower_count": 89000000,
        "description": "Singer, songwriter, actress",
        "country": "USA",
    },
    {
        "name": "Post Malone",
        "follower_count": 109000000,
        "description": "Rapper, singer, songwriter",
        "country": "USA",
    },
    {
        "name": "The Weeknd",
        "follower_count": 137000000,
        "description": "Singer, songwriter, producer",
        "country": "Canada",
    },
    {
        "name": "Billie Eilish",
        "follower_count": 118000000,
        "description": "Singer, songwriter",
        "country": "USA",
    },
    {
        "name": "Harry Styles",
        "follower_count": 236000000,
        "description": "Singer, actor, songwriter",
        "country": "United Kingdom",
    },
    {
        "name": "Shawn Mendes",
        "follower_count": 125000000,
        "description": "Singer, songwriter, model",
        "country": "Canada",
    },
    {
        "name": "Camila Cabello",
        "follower_count": 123000000,
        "description": "Singer, songwriter, dancer",
        "country": "Cuba",
    },
    {
        "name": "Zac Efron",
        "follower_count": 165000000,
        "description": "Actor, dancer, singer",
        "country": "USA",
    },
    {
        "name": "Vanessa Hudgens",
        "follower_count": 134000000,
        "description": "Actress, singer, dancer",
        "country": "USA",
    },
    {
        "name": "Tom Holland",
        "follower_count": 217000000,
        "description": "Actor, producer",
        "country": "United Kingdom",
    },
    {
        "name": "Robert Pattinson",
        "follower_count": 31000000,
        "description": "Actor, producer, musician",
        "country": "United Kingdom",
    },
    {
        "name": "Scarlett Johansson",
        "follower_count": 62000000,
        "description": "Actress, singer",
        "country": "USA",
    },
    {
        "name": "Margot Robbie",
        "follower_count": 77000000,
        "description": "Actress, producer",
        "country": "Australia",
    },
    {
        "name": "Ryan Reynolds",
        "follower_count": 118000000,
        "description": "Actor, entrepreneur",
        "country": "Canada",
    },
    {
        "name": "Blake Lively",
        "follower_count": 84000000,
        "description": "Actress, businesswoman",
        "country": "USA",
    },
    {
        "name": "Priyanka Chopra",
        "follower_count": 94000000,
        "description": "Actress, singer, producer",
        "country": "India",
    },
    {
        "name": "Deepika Padukone",
        "follower_count": 84000000,
        "description": "Actress, producer",
        "country": "India",
    },
    {
        "name": "Aishwarya Rai",
        "follower_count": 75000000,
        "description": "Actress, model",
        "country": "India",
    },
    {
        "name": "Ranveer Singh",
        "follower_count": 69000000,
        "description": "Actor",
        "country": "India",
    },
    {
        "name": "Randeep Hooda",
        "follower_count": 15000000,
        "description": "Actor, producer",
        "country": "India",
    },
    {
        "name": "Varun Dhawan",
        "follower_count": 85000000,
        "description": "Actor, dancer",
        "country": "India",
    },
    {
        "name": "Sidharth Malhotra",
        "follower_count": 68000000,
        "description": "Actor",
        "country": "India",
    },
    {
        "name": "Kareena Kapoor Khan",
        "follower_count": 113000000,
        "description": "Actress, producer",
        "country": "India",
    },
    {
        "name": "Alia Bhatt",
        "follower_count": 89000000,
        "description": "Actress, producer, singer",
        "country": "India",
    },
    {
        "name": "Shraddha Kapoor",
        "follower_count": 79000000,
        "description": "Actress, singer",
        "country": "India",
    },
    {
        "name": "Jacqueline Fernandez",
        "follower_count": 76000000,
        "description": "Actress, dancer, model",
        "country": "Sri Lanka",
    },
    {
        "name": "Katrina Kaif",
        "follower_count": 78000000,
        "description": "Actress, model, dancer",
        "country": "United Kingdom",
    },
    {
        "name": "Anushka Sharma",
        "follower_count": 73000000,
        "description": "Actress, producer",
        "country": "India",
    },
    {
        "name": "Messi Jorge",
        "follower_count": 52000000,
        "description": "Football club account",
        "country": "Argentina",
    },
    {
        "name": "Neymar da Silva",
        "follower_count": 220000000,
        "description": "Professional footballer, Paris Saint-Germain",
        "country": "Brazil",
    },
    {
        "name": "Kylian Mbappé",
        "follower_count": 130000000,
        "description": "Professional footballer, Real Madrid",
        "country": "France",
    },
    {
        "name": "Erling Haaland",
        "follower_count": 165000000,
        "description": "Professional footballer, Manchester City",
        "country": "Norway",
    },
    {
        "name": "Vinicius Jr",
        "follower_count": 98000000,
        "description": "Professional footballer, Real Madrid",
        "country": "Brazil",
    },
    {
        "name": "Jude Bellingham",
        "follower_count": 102000000,
        "description": "Professional footballer, Real Madrid",
        "country": "United Kingdom",
    },
    {
        "name": "Toni Kroos",
        "follower_count": 87000000,
        "description": "Professional footballer, retired",
        "country": "Germany",
    },
    {
        "name": "Sergio Ramos",
        "follower_count": 67000000,
        "description": "Professional footballer",
        "country": "Spain",
    },
    {
        "name": "Gerard Piqué",
        "follower_count": 62000000,
        "description": "Professional footballer, retired",
        "country": "Spain",
    },
    {
        "name": "Antoine Griezmann",
        "follower_count": 81000000,
        "description": "Professional footballer, Atlético Madrid",
        "country": "France",
    },
    {
        "name": "Sergio Agüero",
        "follower_count": 65000000,
        "description": "Professional footballer, retired",
        "country": "Argentina",
    },
    {
        "name": "David Beckham",
        "follower_count": 114000000,
        "description": "Professional footballer, retired",
        "country": "United Kingdom",
    },
    {
        "name": "Roger Federer",
        "follower_count": 28000000,
        "description": "Professional tennis player, retired",
        "country": "Switzerland",
    },
    {
        "name": "Rafael Nadal",
        "follower_count": 28000000,
        "description": "Professional tennis player, retired",
        "country": "Spain",
    },
    {
        "name": "Novak Djokovic",
        "follower_count": 17000000,
        "description": "Professional tennis player",
        "country": "Serbia",
    },
    {
        "name": "Serena Williams",
        "follower_count": 38000000,
        "description": "Professional tennis player",
        "country": "USA",
    },
    {
        "name": "Venus Williams",
        "follower_count": 4500000,
        "description": "Professional tennis player",
        "country": "USA",
    },
    {
        "name": "Cristiano Ronaldo Jr",
        "follower_count": 5000000,
        "description": "Football player, son of Cristiano Ronaldo",
        "country": "Portugal",
    },
    {
        "name": "LeBron James",
        "follower_count": 159000000,
        "description": "Professional basketball player, LA Lakers",
        "country": "USA",
    },
    {
        "name": "Stephen Curry",
        "follower_count": 81000000,
        "description": "Professional basketball player, Golden State Warriors",
        "country": "USA",
    },
    {
        "name": "Kevin Durant",
        "follower_count": 56000000,
        "description": "Professional basketball player",
        "country": "USA",
    },
    {
        "name": "Luka Dončić",
        "follower_count": 39000000,
        "description": "Professional basketball player, Dallas Mavericks",
        "country": "Slovenia",
    },
    {
        "name": "Nikola Jokic",
        "follower_count": 25000000,
        "description": "Professional basketball player, Denver Nuggets",
        "country": "Serbia",
    },
    {
        "name": "Giannis Antetokounmpo",
        "follower_count": 39000000,
        "description": "Professional basketball player, Milwaukee Bucks",
        "country": "Greece",
    },
    {
        "name": "Jayson Tatum",
        "follower_count": 32000000,
        "description": "Professional basketball player, Boston Celtics",
        "country": "USA",
    },
    {
        "name": "Mike Tyson",
        "follower_count": 11000000,
        "description": "Professional boxer, retired",
        "country": "USA",
    },
    {
        "name": "Floyd Mayweather",
        "follower_count": 35000000,
        "description": "Professional boxer, retired",
        "country": "USA",
    },
    {
        "name": "Conor McGregor",
        "follower_count": 42000000,
        "description": "Professional mixed martial artist",
        "country": "Ireland",
    },
    {
        "name": "Elon Musk",
        "follower_count": 42000000,
        "description": "Entrepreneur, CEO Tesla",
        "country": "South Africa",
    },
    {
        "name": "Mark Zuckerberg",
        "follower_count": 10000000,
        "description": "Entrepreneur, founder Facebook",
        "country": "USA",
    },
    {
        "name": "Bill Gates",
        "follower_count": 4800000,
        "description": "Philanthropist, founder Microsoft",
        "country": "USA",
    },
    {
        "name": "Jeff Bezos",
        "follower_count": 2500000,
        "description": "Entrepreneur, founder Amazon",
        "country": "USA",
    },
]
