print("Welcome to the Band Name Generator.")
print("What's name of the city you grew up in?")
input_city = input()
print("What's your pet's name?")
input_pet = input()
print("Your band name could be " + input_city + " " + input_pet)